### ISSUE TITLE
Why only high-level control?

### ISSUE THREAD

**Issue by Lr-2002** [Maddy1206/quadruped_py_control#4]
Hello, maddy
I'm trying to fix the sdk to python for reinforcenment learnning 
But you mentioned that this repo is only for High-level?
Could you tell me whether is there difference between re-write the low-level function
Maybe you just need High level cmd?

**Comment by Maddy1206** [comment]
This repo is a work in progress, so not everything has been done or tried yet.

You can try instantiating low level functionality by rewriting the python files with

`udp = sdk.UDP(LOWLEVEL, BASIC)`
`cmd = sdk.LowCmd()`
`state = sdk.LowState()`

But keep in mind that in the `.cpp` files there is an instance of `Safety safe;`, which is not called in the python scripts.

edit: typo

**Comment by Maddy1206** [comment]
@Lr-2002 

Have you had any success?

**Comment by Lr-2002** [comment]
Yep, i'm trying.Thx for your help
I'll try later and give you feedback

**Comment by Lr-2002** [comment]
OK,problem solved
Thx a lot
