### ISSUE TITLE
no running

### ISSUE THREAD

**Issue by biubiuci** [Maddy1206/quadruped_py_control#5]
Hello, while running this example_walk.py, the mechanical dog is not moving. May I ask what's going on

**Comment by Maddy1206** [comment]
If you want help you need to offer more information first:

- State your experience with the robot.
- What kind of robot dog do you use?
- Which SDK are you using?
- Did you build the project?
- What sports_mode version are you using?

Please answer these questions and if you don't know the answer, write N/A.

**Comment by Maddy1206** [comment]
Closed due to inactivity.
